// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeint.proto

package proto_gen;

/**
 * Protobuf type {@code exchange_rates.ExchangeRateOpArguments}
 */
public  final class ExchangeRateOpArguments extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:exchange_rates.ExchangeRateOpArguments)
    ExchangeRateOpArgumentsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExchangeRateOpArguments.newBuilder() to construct.
  private ExchangeRateOpArguments(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExchangeRateOpArguments() {
    arg_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExchangeRateOpArguments(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            arg_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto_gen.ExchangeRateProto.internal_static_exchange_rates_ExchangeRateOpArguments_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto_gen.ExchangeRateProto.internal_static_exchange_rates_ExchangeRateOpArguments_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto_gen.ExchangeRateOpArguments.class, proto_gen.ExchangeRateOpArguments.Builder.class);
  }

  public static final int ARG_FIELD_NUMBER = 1;
  private int arg_;
  /**
   * <code>.exchange_rates.CurrencyType arg = 1;</code>
   */
  public int getArgValue() {
    return arg_;
  }
  /**
   * <code>.exchange_rates.CurrencyType arg = 1;</code>
   */
  public proto_gen.CurrencyType getArg() {
    @SuppressWarnings("deprecation")
    proto_gen.CurrencyType result = proto_gen.CurrencyType.valueOf(arg_);
    return result == null ? proto_gen.CurrencyType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (arg_ != proto_gen.CurrencyType.PLN.getNumber()) {
      output.writeEnum(1, arg_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (arg_ != proto_gen.CurrencyType.PLN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, arg_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto_gen.ExchangeRateOpArguments)) {
      return super.equals(obj);
    }
    proto_gen.ExchangeRateOpArguments other = (proto_gen.ExchangeRateOpArguments) obj;

    if (arg_ != other.arg_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ARG_FIELD_NUMBER;
    hash = (53 * hash) + arg_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto_gen.ExchangeRateOpArguments parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto_gen.ExchangeRateOpArguments parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto_gen.ExchangeRateOpArguments parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto_gen.ExchangeRateOpArguments parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto_gen.ExchangeRateOpArguments prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code exchange_rates.ExchangeRateOpArguments}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exchange_rates.ExchangeRateOpArguments)
      proto_gen.ExchangeRateOpArgumentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto_gen.ExchangeRateProto.internal_static_exchange_rates_ExchangeRateOpArguments_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto_gen.ExchangeRateProto.internal_static_exchange_rates_ExchangeRateOpArguments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto_gen.ExchangeRateOpArguments.class, proto_gen.ExchangeRateOpArguments.Builder.class);
    }

    // Construct using proto_gen.ExchangeRateOpArguments.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      arg_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto_gen.ExchangeRateProto.internal_static_exchange_rates_ExchangeRateOpArguments_descriptor;
    }

    @java.lang.Override
    public proto_gen.ExchangeRateOpArguments getDefaultInstanceForType() {
      return proto_gen.ExchangeRateOpArguments.getDefaultInstance();
    }

    @java.lang.Override
    public proto_gen.ExchangeRateOpArguments build() {
      proto_gen.ExchangeRateOpArguments result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto_gen.ExchangeRateOpArguments buildPartial() {
      proto_gen.ExchangeRateOpArguments result = new proto_gen.ExchangeRateOpArguments(this);
      result.arg_ = arg_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto_gen.ExchangeRateOpArguments) {
        return mergeFrom((proto_gen.ExchangeRateOpArguments)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto_gen.ExchangeRateOpArguments other) {
      if (other == proto_gen.ExchangeRateOpArguments.getDefaultInstance()) return this;
      if (other.arg_ != 0) {
        setArgValue(other.getArgValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto_gen.ExchangeRateOpArguments parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto_gen.ExchangeRateOpArguments) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int arg_ = 0;
    /**
     * <code>.exchange_rates.CurrencyType arg = 1;</code>
     */
    public int getArgValue() {
      return arg_;
    }
    /**
     * <code>.exchange_rates.CurrencyType arg = 1;</code>
     */
    public Builder setArgValue(int value) {
      arg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.exchange_rates.CurrencyType arg = 1;</code>
     */
    public proto_gen.CurrencyType getArg() {
      @SuppressWarnings("deprecation")
      proto_gen.CurrencyType result = proto_gen.CurrencyType.valueOf(arg_);
      return result == null ? proto_gen.CurrencyType.UNRECOGNIZED : result;
    }
    /**
     * <code>.exchange_rates.CurrencyType arg = 1;</code>
     */
    public Builder setArg(proto_gen.CurrencyType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      arg_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.exchange_rates.CurrencyType arg = 1;</code>
     */
    public Builder clearArg() {
      
      arg_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:exchange_rates.ExchangeRateOpArguments)
  }

  // @@protoc_insertion_point(class_scope:exchange_rates.ExchangeRateOpArguments)
  private static final proto_gen.ExchangeRateOpArguments DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto_gen.ExchangeRateOpArguments();
  }

  public static proto_gen.ExchangeRateOpArguments getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeRateOpArguments>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeRateOpArguments>() {
    @java.lang.Override
    public ExchangeRateOpArguments parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExchangeRateOpArguments(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExchangeRateOpArguments> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExchangeRateOpArguments> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto_gen.ExchangeRateOpArguments getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

