// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeint.proto

package proto_gen;

public final class ExchangeRateProto {
  private ExchangeRateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_rates_ExchangeRateOpArguments_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_rates_ExchangeRateOpArguments_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_rates_ExchangeRateOpResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_rates_ExchangeRateOpResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021exchangeint.proto\022\016exchange_rates\"D\n\027E" +
      "xchangeRateOpArguments\022)\n\003arg\030\001 \001(\0162\034.ex" +
      "change_rates.CurrencyType\"#\n\024ExchangeRat" +
      "eOpResult\022\013\n\003res\030\001 \001(\001*)\n\014CurrencyType\022\007" +
      "\n\003PLN\020\000\022\007\n\003EUR\020\001\022\007\n\003GBP\020\0022{\n\023ExchangeRat" +
      "eService\022d\n\017getExchangeRate\022\'.exchange_r" +
      "ates.ExchangeRateOpArguments\032$.exchange_" +
      "rates.ExchangeRateOpResult\"\0000\001B&\n\tproto_" +
      "genB\021ExchangeRateProtoP\001\242\002\003HLWb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_exchange_rates_ExchangeRateOpArguments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exchange_rates_ExchangeRateOpArguments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_rates_ExchangeRateOpArguments_descriptor,
        new java.lang.String[] { "Arg", });
    internal_static_exchange_rates_ExchangeRateOpResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_exchange_rates_ExchangeRateOpResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_rates_ExchangeRateOpResult_descriptor,
        new java.lang.String[] { "Res", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
