// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeint.proto

package proto_gen;

public interface ExchangeRateOpResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exchange_rates.ExchangeRateOpResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double res = 1;</code>
   */
  double getRes();
}
