// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: exchangeint.proto

package proto_gen;

public interface ExchangeRateOpArgumentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exchange_rates.ExchangeRateOpArguments)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.exchange_rates.CurrencyType arg = 1;</code>
   */
  int getArgValue();
  /**
   * <code>.exchange_rates.CurrencyType arg = 1;</code>
   */
  proto_gen.CurrencyType getArg();
}
